### ISSUE TITLE
Bug: Error importing purecss

### ISSUE THREAD

**Issue by che-wf** [rubysamurai/purecss-sass#1]
I'm using npm to install purecss-sass. When I enter the following into scss, I'm getting an error:

```
@import 'purecss/base';
@import 'purecss/grids-responsive';
@import 'purecss/buttons';
```

The error I'm getting is `Error: File to import not found or unreadable: purecss/base.
        on line 1 of src/scss/style.scss`. Is this meant for using with Grunt?

**Comment by rubysamurai** [comment]
That part of readme about individual Sass components usage is actually refers to Rails and Compass workflow and I apologize for confusion.

npm pulls all `.scss` files to `purecss-sass/vendor/assets/stylesheets/purecss` (this folder structure is coming from Ruby gem file). And import path should be changed to something like this:

```
@import 'purecss-sass/vendor/assets/stylesheets/purecss/base';
@import 'purecss-sass/vendor/assets/stylesheets/purecss/grids-responsive';
@import 'purecss-sass/vendor/assets/stylesheets/purecss/buttons';
```

**Comment by che-wf** [comment]
Yeah, I ended up having to enter 
`@import '../../node_modules/purecss-sass/vendor/assets/stylesheets/purecss';`

**Comment by salzig** [comment]
@jbcoder @rubysamurai works if you prepend a `~`. 
```
@import '~purecss-sass/vendor/assets/stylesheets/purecss/base';
@import '~purecss-sass/vendor/assets/stylesheets/purecss/grids-responsive';
@import '~purecss-sass/vendor/assets/stylesheets/purecss/buttons';
```
