### ISSUE TITLE
Importing in jekyll doesn't work

### ISSUE THREAD

**Issue by daiyi** [rubysamurai/purecss-sass#4]
Using `@import "purecss";` in jekyll sass files doesn't work:

```
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/main.scss':
                    File to import not found or unreadable: purecss. Load path: /home/user/project/_sass on line 2
jekyll 3.3.1 | Error:  File to import not found or unreadable: purecss.

```

How do I make jekyll aware of purecss?

**Comment by rubysamurai** [comment]
Using custom `sass` files with Jekyll require quite a few additional steps. Basic guide can be found in [official Jekyll docs](https://jekyllrb.com/docs/assets/) and some advanced tips, for instance, [here](http://markdotto.com/2014/09/25/sass-and-jekyll/).

Assuming purecss-sass was installed with npm

1) Create folder inside your Jekyll project called `_sass` and copy `purecss` folder from `~/node_modules/purecss-sass/vendor/assets/stylesheets`

2) Create folder inside your Jekyll project called `css` and copy `_purecss.scss` file from `~/node_modules/purecss-sass/vendor/assets/stylesheets`

3) Rename `_purecss.scss` file, that you just copied, to `purecss.scss`, open it and add at the top these lines:
 
```
---
# Front matter comment to ensure Jekyll properly reads file.
---
```

Now you can include purecss inside your Jekyll layout file:
```
<link rel="stylesheet" href="/css/purecss.css">
```

**Comment by daiyi** [comment]
Hm, ok. I was hoping there would be a more clean solution than manually copy-pasting, because the point of adding the purecss files through rubygems is so they can be managed in a consistent way. I suppose I'll do it manually if it's the only way. Thanks!

**Comment by Hermanya** [comment]
I found https://simpleit.rocks/how-to-add-bootstrap-4-to-jekyll-the-right-way/ useful
